<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Blazor-ApexCharts" Version="6.0.2" />
	<PackageReference Include="Blazored.LocalStorage" Version="4.3.0" />
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.1" PrivateAssets="all" />
	<PackageReference Include="MudBlazor" Version="9.11.0" />
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Shared\NovinApp.Shared.csproj" />

  </ItemGroup>

</Project>
