// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovinApp.Server.MyContext;

#nullable disable

namespace NovinApp.Server.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovinApp.Shared.Exams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdQuestion")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("selectedOption")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("NovinApp.Shared.PsychologyTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighSchoolBranchesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Moshaver")
                        .HasColumnType("int");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryScore")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScoresJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StudentNationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuitableCareersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityMajorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PsychologyTestResults");
                });

            modelBuilder.Entity("NovinApp.Shared.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender_specific")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Groups")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfOptions")
                        .HasColumnType("int");

                    b.Property<bool?>("Option1IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option1Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option1Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Option2IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option2Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option2Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Option3IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option3Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option3Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Option4IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option4Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option4Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Option5IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option5Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option5Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Option6IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("Option6Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Option6Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("NovinApp.Shared.Report_students", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamStatictics_PresentCount")
                        .HasColumnType("int");

                    b.Property<int>("GenderStatistics_PresentCount")
                        .HasColumnType("int");

                    b.Property<string>("GetStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetWeekness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeySheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_Student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_school")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionStatistics_PresentCount")
                        .HasColumnType("int");

                    b.Property<int>("SchoolStatistics_PresentCount")
                        .HasColumnType("int");

                    b.Property<string>("StringName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentCode")
                        .HasColumnType("bigint");

                    b.Property<string>("Student_FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_LevelNameString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Region_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Student_School_Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Student_School_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Section_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Total_Blank")
                        .HasColumnType("real");

                    b.Property<float>("Total_False")
                        .HasColumnType("real");

                    b.Property<float>("Total_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("Total_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Total_Percent")
                        .HasColumnType("real");

                    b.Property<float>("Total_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("Total_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("Total_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("Total_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("Total_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("Total_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("Total_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("Total_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Total_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("Total_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("Total_True")
                        .HasColumnType("real");

                    b.Property<string>("UploadDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("lesson10_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson10_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson10_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson10_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson10_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson10_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson11_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson11_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson11_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson11_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson11_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson12_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson12_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson12_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson12_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson12_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson13_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson13_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson13_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson13_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson13_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson14_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson14_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson14_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson14_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson14_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson1_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson1_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson1_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson1_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson1_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson2_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson2_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson2_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson2_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson2_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson3_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson3_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson3_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson3_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson3_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson4_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson4_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson4_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson4_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson4_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson5_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson5_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson5_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson5_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson5_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson6_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson6_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson6_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson6_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson6_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson7_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson7_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson7_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson7_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson7_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson8_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson8_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson8_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson8_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson8_True")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_Blank")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_False")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_MaxTararz")
                        .HasColumnType("real");

                    b.Property<string>("lesson9_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson9_Percent")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_PercentAvarage")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_PercentMax")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_PercentMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_RankArea")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_RankSchool")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_RankSex")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_RankTotal")
                        .HasColumnType("real");

                    b.Property<string>("lesson9_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lesson9_Taraz")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_TarazMin")
                        .HasColumnType("real");

                    b.Property<float>("lesson9_True")
                        .HasColumnType("real");

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Report_students");
                });

            modelBuilder.Entity("NovinApp.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Id_Moshaver")
                        .HasColumnType("int");

                    b.Property<int?>("Id_School")
                        .HasColumnType("int");

                    b.Property<string>("Moshaver")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("code_meli")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("rowId")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NovinApp.Shared.Exams", b =>
                {
                    b.HasOne("NovinApp.Shared.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.HasOne("NovinApp.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Question");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
